### ISSUE TITLE
gulp build - SyntaxError

### ISSUE THREAD

**Issue by coquiNinja** [Netflix/lemur-docker#11]
Morning, 
I am trying to evaluate lemur to be incorporated into my company but I am having some installation issue/s. 
(if this is not the forum to discuss this please let me know) 
I downloaded the Docker ToolBox and followed the instructions but at the end I am getting a SysntaxError: Use of const in strict mode.  referring to  ../node_modules/is-number-like/lib/index.js line2.
const isNumber = require(lodash.isfinite)
Any help will be very appreciated! 
Thanks!

**Comment by kevgliss** [comment]
I haven't that particular error before... could you post the full stacktrace?

**Comment by coquiNinja** [comment]
I got the lemur:/var/log/docker.log file but it doesn't have info about this error... so I took a picture of my screen and I am attaching it... if you know where can I get a better log file please let me know.  
I research this error aka google it... and it said to append "--harmony" in the gulp command but not sure where to put it... Thanks!
![lemur_docker_gulp_error](https://cloud.githubusercontent.com/assets/24531678/21156718/b9d26c46-c12b-11e6-96cb-18bc6d770d46.PNG)
