### ISSUE TITLE
Add DigiCert Support

### ISSUE THREAD

**Issue by jgamblin** [Netflix/lemur-docker#29]
Would it be possible to add digicert support to the docker image or is it already since it is part of the base?

**Comment by kevgliss** [comment]
Digicert is already included in Lemur core, you would have to modify the imagine with your own credentials to enable it:

See:
https://github.com/Netflix/lemur-docker/blob/master/web/lemur.conf.py#L62
and
http://lemur.readthedocs.io/en/latest/administration.html#digicert-issuer-plugin
