### ISSUE TITLE
unable to locate credentials

### ISSUE THREAD

**Issue by testvm74** [Netflix/lemur-docker#34]
Plan is to create LE certificate with route 53 
I tried setting 
~/.aws/credentials as below
[default]
aws_access_key_id=xxxx
aws_secret_access_key=xxxxxxxxxxxxxxxxxxxx
and environment variables as well. 
But no luck. 
::
::
lemur-web_1    | Connecting with directory at https://acme-v01.api.letsencrypt.org/directory
lemur-web_1    | Connected: https://acme-v01.api.letsencrypt.org/acme/reg/3557XXX
lemur-web_1    | Fetching domains
lemur-web_1    | Got these domains: ['test.domain.com']
lemur-web_1    | Starting DNS challenge for test.domain.com
lemur-web_1    | [2018-05-26 00:06:25,973] ERROR in schema: Unable to locate credentials
lemur-web_1    | Traceback (most recent call last):
lemur-web_1    |   File "/usr/local/src/lemur/lemur/common/schema.py", line 160, in decorated_function
lemur-web_1    |     resp = f(*args, **kwargs)
lemur-web_1    |   File "/usr/local/src/lemur/lemur/certificates/views.py", line 270, in post
lemur-web_1    |     cert = service.create(**data)
::
::
lemur-web_1    | botocore.exceptions.NoCredentialsError: Unable to locate credentials
Can you point out where can I set  credentials details for AWS?

Thanks in advance.

**Comment by kevgliss** [comment]
I believe it this is a docker question not a question specific to lemur-docker (we don't do anything special for aws here).

**Comment by kevgliss** [comment]
Closed for inactivity.
