### ISSUE TITLE
Default username/password not working?

### ISSUE THREAD

**Issue by superscott** [Netflix/lemur-docker#4]
Docker install went fine, and everything appears to be "working" but when logging with lemur/password I get a 401 error back.

![screen shot 2015-10-28 at 3 56 15 pm](https://cloud.githubusercontent.com/assets/1940659/10805655/98c0ccb6-7d8c-11e5-94ee-6e3a1f651705.png)

sorry for this being the first public issue :D

**Comment by kevgliss** [comment]
Sorry about this, we upgraded Lemur and forgot to update the docker! I have also ensured that the docker was pinning to a version that works, so we shouldn't introduce any breaking changes to the docker unknowingly. Let me know if you run into any issues.
