### ISSUE TITLE
Root CAs and Certs missing in UI from all but dashboard after containers restarted

### ISSUE THREAD

**Issue by jibbajabber** [Netflix/lemur-docker#61]
Problem: **CAs and certs missing when containers restarted**
Expectation: **CAs and certs created are visible under Authorities and Certificates**
OS: Fresh CentOS 7 install `7.9.2009 (Core)`
Docker Engine: `20.10.5`
Docker Compose: `1.29.0`
Reproduce steps:
* Bring the project up with `docker-compose up` (runs in foreground)
* Log in using default credentials
* Create a Cryptography plugin root CA
* Control-C to stop containers
* Bring the project back up with `docker-compose up`
* Log in using default credentials
* Check Authorities and Certificates and no items are present
* Check dashboard and Issuers will show 1 selfsigned

After destroying with `docker-compose down` this issue still persists

**Several python tracebacks are in the container output which can be found here =>** https://pastebin.com/E6LzNRNA

I thought best to raise here first as it might be an issue with postgres container or something within the compose stack. Happy to raise in Lemur issue tracker if more appropriate.

**Comment by jtschladen** [comment]
I believe this is the cause:
```
lemur_1     |   File "/opt/venv/lib/python3.8/site-packages/cryptography/fernet.py", line 194, in decrypt
lemur_1     |     raise InvalidToken
lemur_1     | cryptography.fernet.InvalidToken
```

As noted in the [README](https://github.com/Netflix/lemur-docker#default-config), these containers generate random secrets on startup - [this one](https://github.com/Netflix/lemur-docker/blob/07c9c5ec8ce7cbd4024063006e970667fc283b34/lemur.conf.py#L33-L35) is the one causing you trouble, I believe. If you want to use the containers repeatedly, you'll need to set a constant secret (you can use `.lemur.env.dist`).

Feel free to raise a PR to update the README if you can think of a way to make this shortcoming clearer - I realize it's not exactly obvious.

**Comment by jibbajabber** [comment]
Thanks again @jtschladen for such a quick response! Sorry, this is clearly user-error on my part (again) ☹️ 
Thank you for being awesome 😄

**Comment by jtschladen** [comment]
At least this was an easier one than yesterday's - and you caught me at a good time. Happy to help!
