### ISSUE TITLE
Ability to log to standard out as JSON.

### ISSUE THREAD

**Issue by mik373** [Netflix/lemur-docker#7]
Since we are running Lemur inside docker on CoreOS, we'd like to be able to log in JSON format to stdout.  That way our Docker logger driver can login into journalctl which delivers the logs into our cloud solution.  As far as we can tell there is no way to configure this via the config file currently.

**Comment by kevgliss** [comment]
We currently don't deploy to docker, this also seems like it should be an issue/enhancement on the core project as this repo mainly serves as an example and to get users up and running without too much effort. 

That being said, if you feel like you have a clean way of supporting both standard logging and json logging (perhaps with a configuration option?), then I would be more than happy to include it in the core.

Something like this may be helpful.
https://github.com/madzak/python-json-logger
