### ISSUE TITLE
Receiving a bad request when trying to create a new authority

### ISSUE THREAD

**Issue by thevarunshah** [Netflix/lemur-docker#9]
When trying to create a new authority, I receive a 400 bad request when it tries to post to /api/1/authorities.
Could it be possible that the docker container doesn't have the last stable release?

**Comment by kevgliss** [comment]
I did release a new version recently. Although the older version *should* still work. I will try and update this docker image to go along with it this week.

**Comment by kevgliss** [comment]
I've upgraded the image to the latest stable release. I wonder though, how are you creating an authority? By default the only plugin included with Lemur is Verisign/Symantec, although there are others floating around (Digicert, EBJCA, openssl, etc.). The default root certificate is not included in the docker default.conf.py as which one you use is highly dependent on the use case. 

Lemur is not an certificate authority itself and relies on other CA's to actually issue certificates.

**Comment by thevarunshah** [comment]
Thanks for the upgrade! 
I guess my problem was that I wasn't including the root cert - didn't fully understand the functionality - thanks for the clarification.
